# Generated by Django 5.2.11 on 2026-02-26 14:38

from django.conf import settings
from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_special_users(apps, schema_editor):
    User = apps.get_model("accounts", "User")

    system_email = getattr(settings, "SYSTEM_USER_EMAIL", "system@local.invalid")
    anon_email = getattr(settings, "ANONYMOUS_USER_EMAIL", "anonymous@local.invalid")

    unusable = make_password(None)

    # SYSTEM USER
    system_user, created = User.objects.get_or_create(
        email=system_email,
        defaults={
            "is_active": True,
            "is_staff": False,
            "is_superuser": False,
            "password": unusable,
        },
    )
    if system_user.password == "":
        system_user.password = unusable
        system_user.save(update_fields=["password"])

    # ANONYMOUS USER (usually inactive)
    anon_user, created = User.objects.get_or_create(
        email=anon_email,
        defaults={
            "is_active": False,
            "is_staff": False,
            "is_superuser": False,
            "password": unusable,
        },
    )
    if anon_user.password == "":
        anon_user.password = unusable
        anon_user.save(update_fields=["password"])


def reverse_noop(apps, schema_editor):
    # Usually you don't want to delete these automatically on reverse.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RunPython(create_special_users, reverse_noop),
    ]
