# Generated by Django 5.2.11 on 2026-03-02 21:35

import django.db.models.deletion
import lib_util.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PREAUTHORIZED', 'Preauthorized'), ('RUNNER_ACCEPTED', 'Runner accepted'), ('SHOPPING', 'Shopping'), ('PROOF_UPLOADED', 'Proof uploaded'), ('DELIVERING', 'Delivering'), ('DELIVERED', 'Delivered'), ('AWAITING_CONFIRMATION', 'Awaiting confirmation'), ('CONFIRMED', 'Confirmed'), ('CAPTURED', 'Captured'), ('DISPUTED', 'Disputed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], default='CREATED', max_length=32)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('preferred_store_1', models.CharField(blank=True, max_length=255)),
                ('preferred_store_2', models.CharField(blank=True, max_length=255)),
                ('delivery_address', models.TextField()),
                ('delivery_postcode', models.CharField(max_length=10)),
                ('spending_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('substitution_mode', models.CharField(choices=[('ALLOW_SUBSTITUTE', 'Allow Substitute'), ('ASK_FIRST', 'Ask First'), ('NO_SUBSTITUTE', 'No Substitute')], default='ASK_FIRST', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('acceptance_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('substitution_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_code_hash', models.CharField(blank=True, max_length=128)),
                ('delivery_code_attempts', models.PositiveSmallIntegerField(default=0)),
                ('delivery_code_locked', models.BooleanField(default=False)),
                ('total_spend', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('delivery_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('creation_user', lib_util.fields.UpdateUserField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
                ('last_modified_user', lib_util.fields.UpdateUserField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('runner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='runner_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('creation_user', lib_util.fields.UpdateUserField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_user', lib_util.fields.UpdateUserField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orders.order')),
            ],
            options={
                'ordering': ['creation_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank='', max_length=255)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PURCHASED', 'Purchased'), ('SUBSTITUTED', 'Substituted'), ('REMOVED', 'Removed')], default='REQUESTED', max_length=20)),
                ('substitution_requested_at', models.DateTimeField(blank=True, null=True)),
                ('substitution_resolved_at', models.DateTimeField(blank=True, null=True)),
                ('substitution_note', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('creation_user', lib_util.fields.UpdateUserField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_user', lib_util.fields.UpdateUserField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProofOfPurchase',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_store_1', models.CharField(blank=True, max_length=120)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='proofs/receipts/')),
                ('basket_photo', models.ImageField(blank=True, null=True, upload_to='proofs/baskets/')),
                ('creation_user', lib_util.fields.UpdateUserField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_user', lib_util.fields.UpdateUserField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProofItemPhoto',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='proofs/items/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creation_user', lib_util.fields.UpdateUserField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_user', lib_util.fields.UpdateUserField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_photos', to='orders.proofofpurchase')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RunnerRating',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField()),
                ('attributes', models.JSONField(blank=True, default=list)),
                ('feedback', models.TextField(blank=True)),
                ('creation_user', lib_util.fields.UpdateUserField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
                ('last_modified_user', lib_util.fields.UpdateUserField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='orders.order')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubstitutionRequest',
            fields=[
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_item', models.CharField(max_length=200)),
                ('suggested_item', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('creation_user', lib_util.fields.UpdateUserField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('last_modified_user', lib_util.fields.UpdateUserField(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
